# string = input('enter your string:')
# output_str = ''
# for ch in string:
#     if ch not in output_str:
#         output_str = output_str + ch
#
#
# print(output_str)

# string = "Hello, World!"
# substring = string[7:12:2]#slicing...
# print(substring)


s = '''India, officially the Republic of India (ISO: Bhārat Gaṇarājya),[25] is a country in South Asia. It is the seventh-largest country by area and the most populous country in the world.[26][27] Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[j] China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand, Myanmar, and Indonesia.
Modern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago.[28][29][30] Their long occupation, initially in varying forms of isolation as hunter-gatherers, has made the region highly diverse, second only to Africa in human genetic diversity.[31] Settled life emerged on the subcontinent in the western margins of the Indus river basin 9,000 years ago, evolving gradually into the Indus Valley Civilisation of the third millennium BCE.[32] By 1200 BCE, an archaic form of Sanskrit, an Indo-European language, had diffused into India from the northwest.[33][34] Its evidence today is found in the hymns of the Rigveda. Preserved by a resolutely vigilant oral tradition, the Rigveda records the dawning of Hinduism in India.[35] The Dravidian languages of India were supplanted in the northern and western regions.[36] By 400 BCE, stratification and exclusion by caste had emerged within Hinduism,[37] and Buddhism and Jainism had arisen, proclaiming social orders unlinked to heredity.[38] Early political consolidations gave rise to the loose-knit Maurya and Gupta Empires based in the Ganges Basin.[39] Their collective era was suffused with wide-ranging creativity,[40] but also marked by the declining status of women,[41] and the incorporation of untouchability into an organised system of belief.[k][42] In South India, the Middle kingdoms exported Dravidian-langu
India has been a federal republic since 1950, governed through a democratic parliamentary system. It is a pluralistic, multilingual and multi-ethnic society. India's population grew from 361 million in 1951 to almost 1.4 billion in 2022.[62] During the same time, its nominal per capita income increased from US$64 annually to US$1,498, and its literacy rate from 16.6% to 74%. From being a comparatively destitute country in 1951,[63] India has become a fast-growing major economy and a hub for information technology services, with an expanding middle class.[64] It has a space programme which includes several planned or completed extraterrestrial missions. Indian movies, music, and spiritual teachings play an increasing role in global culture.[65] India has substantially reduced its rate of poverty, though at the cost of increasing economic inequality.[66] India is a nuclear-weapon state, which ranks high in military expenditure. It has disputes over Kashmir with its neighbours, Pakistan and China, unresolved since the mid-20th century.[67] Among the socio-economic challenges India faces are gender inequality, child malnutrition,[68] and rising levels of air pollution.[69] India's land is megadiverse, with four biodiversity hotspots.[70] Its forest cover comprises 21.7% of its area.[71] India's wildlife, which has traditionally been viewed with tolerance in India's culture,[72] is supported among these forests, and elsewhere, in protected habitats.''